AllCops:
  RubyInterpreters:
    - ruby

  Include:
    - '**/*.rb'
    - '**/Gemfile'
  Exclude:
    - template.rb

  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  StyleGuideCopsOnly: false
  NewCops: enable
  UseCache: true
  SuggestExtensions: false

### Layout
Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - n
    - x
    - y
  AllowNamesEndingInNumbers: true

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Security/Eval:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyHeredoc:
  AutoCorrect: disabled

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/PerlBackrefs:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/LineLength:
  Enabled: false
